### ISSUE TITLE
No module named 'lxml.etree error

### ISSUE THREAD

**Issue by pvoudouris** [GeoCat/qgis-bridge-plugin#1]
This is the error I get when I try to load the plugin. Since this seems like something went wrong in the installation these are the steps I used (windows 10 enterprise, QGIS 3.4)
```
D:\temp>git clone https://github.com/GeoCat/qgis-bridge-plugin.git --recursive

Cloning into 'qgis-bridge-plugin'...
remote: Enumerating objects: 865, done.
remote: Counting objects: 100% (865/865), done.
remote: Compressing objects: 100% (416/416), done.
remote: Total 865 (delta 484), reused 815 (delta 438), pack-reused 0
Receiving objects: 100% (865/865), 1.04 MiB | 2.21 MiB/s, done.
Resolving deltas: 100% (484/484), done.
Submodule 'geocatbridge/libs/bridgecommon' (https://github.com/GeoCat/bridge-common.git) registered for path 'geocatbridge/libs/bridgecommon'
Submodule 'geocatbridge/libs/bridgestyle' (https://github.com/GeoCat/bridge-style.git) registered for path 'geocatbridge/libs/bridgestyle'
Cloning into 'D:/projects/Personal/Consortis_temp/qgis-bridge-plugin/geocatbridge/libs/bridgecommon'...
remote: Enumerating objects: 61, done.
remote: Counting objects: 100% (61/61), done.
remote: Compressing objects: 100% (47/47), done.
remote: Total 61 (delta 28), reused 34 (delta 12), pack-reused 0
Cloning into 'D:/projects/Personal/Consortis_temp/qgis-bridge-plugin/geocatbridge/libs/bridgestyle'...
remote: Enumerating objects: 91, done.
remote: Counting objects: 100% (91/91), done.
remote: Compressing objects: 100% (57/57), done.
remote: Total 91 (delta 39), reused 71 (delta 26), pack-reused 0
Submodule path 'geocatbridge/libs/bridgecommon': checked out 'e9976aa33ce0471d8d41d7aed0396a5b9a7f5aa9'
Submodule path 'geocatbridge/libs/bridgestyle': checked out 'ad1c537f36736c7edf097baf55a4df6e69fd7e22'

```
And then:
```
D:\temp>cd qgis-bridge-plugin

D:\temp\qgis-bridge-plugin>git submodule update --init
```

I then copied the geocatbridge folder into the QGIS3 plugin folder and the full error I get is:
```
ModuleNotFoundError: No module named 'lxml.etree'
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/pano.voudouris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\__init__.py", line 20, in classFactory
    from .plugin import GeocatBridge
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pano.voudouris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\plugin.py", line 20, in 
    from .ui.bridgedialog import BridgeDialog
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pano.voudouris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\ui\bridgedialog.py", line 8, in 
    from .publishwidget import PublishWidget
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pano.voudouris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\ui\publishwidget.py", line 4, in 
    from geocatbridge.publish.servers import geodataServers, metadataServers, GeonetworkServer
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:/Users/pano.voudouris/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\servers.py", line 6, in 
    import lxml.etree as ET
  File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\utils.py", line 672, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'lxml.etree'
```
Where did I go wrong??

**Comment by geographika** [comment]
It looks like the lxml library included in the libs folder isn't compiled so won't work on Windows?

I resolved this with the following approach:

```bat
REM remove the lxml library
rmdir "C:\Program Files\QGIS 3.4\apps\qgis\python\plugins\geocatbridge\libs\lxml" /S /Q

REM activate the py3 QGIS environ and install lxml from pypi
"C:\Program Files\QGIS 3.4\OSGeo4W.bat"
py3_env
pip install lxml
```

I also have to move the contents of `geocatbridge\libs\bridgestyle\bridgestyle` up one folder (and remove the setup.py etc.) or I got at `ModuleNotFoundError: No module named 'bridgestyle.qgis' ` error. 

Following a restart of QGIS these errors were gone. I also applied the #2 pull request. 
I still get the following error:

```
File "C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python/plugins\geocatbridge\processing\publishtogeonetwork.py", line 5, in 
from qgis.core import (QgsSettings, ImportError: cannot import name 'QgsProcessingParameterAuthConfig' from 'qgis.core' (C:/PROGRA~1/QGIS3~1.4/apps/qgis/./python\qgis\core\__init__.py)
```

However I can successfully export a style from the QGIS console using:

```python
from bridgestyle.qgis import saveLayerStyleAsZippedSld
warnings = saveLayerStyleAsZippedSld(iface.activeLayer(), "C:/temp/mystyle.zip")
```

**Comment by volaya** [comment]
The lib included in the libs folder should be fine for Windows (but not in other OSs). We do our development and testing in Windows actually....

The last error you are seeing is because QgsProcessingParameterAuthConfig was added in 3.6, so you need a more recent QGIS. I will update the min version in the metadata
