### ISSUE TITLE
error on load

### ISSUE THREAD

**Issue by gubuntu** [GeoCat/qgis-bridge-plugin#109]
```
ValueError: could not convert string to float: 
Traceback (most recent call last):
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 59, in updateForCurrentLayer
    sld, _, sldWarnings = layerStyleAsSld(layer)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 17, in layerStyleAsSld
    geostyler, icons, warnings = togeostyler.convert(layer)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 32, in convert
    geostyler = processLayer(layer)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 78, in processLayer
    rules.extend(processRule(rule,None,layer.opacity(),layer))
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 393, in processRule
    symbolizers = _createSymbolizers(rule.symbol(),layerOpacity)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 535, in _createSymbolizers
    symbolizer = _createSymbolizer(sl, opacity)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 549, in _createSymbolizer
    symbolizer = _simpleMarkerSymbolizer(sl, opacity)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 676, in _simpleMarkerSymbolizer
    mark = _markGraphic(sl)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 712, in _markGraphic
    size = _symbolProperty(sl, "size", QgsSymbolLayer.PropertySize)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 504, in _symbolProperty
    v = _handleUnits(v, units, propertyConstant)
  File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 462, in _handleUnits
    return float(value) * MM2PIXEL
ValueError: could not convert string to float: 


Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.10.3-A Coruña A Coruña, 0e1f846438 

Python Path:
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.10.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.10.app/Contents/Resources/python
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python
.
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/Users/Shared/data/STI/STI_mergin/STI
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs
/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle```

**Comment by volaya** [comment]
@gubuntu Could you share the layer that you are trying to upload. Actually, the style is what is causing the issue, so that should be enough for us to debug this

Thanks!

**Comment by NyakudyaA** [comment]
Error on loading wms layer
```
TypeError: argument of type 'NoneType' is not iterable 
Traceback (most recent call last):
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 59, in updateForCurrentLayer
    sld, _, sldWarnings = layerStyleAsSld(layer)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/qgis/__init__.py", line 18, in layerStyleAsSld
    sldString, sldWarnings = sld.fromgeostyler.convert(geostyler)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/sld/fromgeostyler.py", line 34, in convert
    featureTypeStyle.append(processRule(rule))
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/sld/fromgeostyler.py", line 64, in processRule
    symbolizers = _createSymbolizers(rule["symbolizers"])
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/sld/fromgeostyler.py", line 72, in _createSymbolizers
    symbolizer = _createSymbolizer(sl)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/sld/fromgeostyler.py", line 94, in _createSymbolizer
    symbolizer = _rasterSymbolizer(sl)
  File "/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web/bridgestyle/sld/fromgeostyler.py", line 149, in _rasterSymbolizer
    if chanName in sl["channelSelection"]:
TypeError: argument of type 'NoneType' is not iterable


Python version: 3.7.5 (default, Nov 20 2019, 09:21:52) [GCC 9.2.1 20191008] 
QGIS version: 3.12.0-București București, exported 

Python Path:
/usr/local/share/qgis/python
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/local/share/qgis/python/plugins
/usr/lib/python37.zip
/usr/lib/python3.7
/usr/lib/python3.7/lib-dynload
/home/admire/.local/lib/python3.7/site-packages
/usr/local/lib/python3.7/dist-packages
/usr/lib/python3/dist-packages
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis2web
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs
/home/admire/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle
```

**Comment by volaya** [comment]
The issue with the WMS layers should be already fixed. Please, next time open a new ticket instead on commenting on an existing one

**Comment by jodygarnett** [comment]
@volaya can this issue be closed now?

**Comment by gubuntu** [comment]
My OP error occurred on plugin load when starting QGIS, not when uploading a style or layer. But it is not happening any more, i.e. fixed.

Just get this in the logger in 3.10 and 3.12 now:

```
2020-04-07T21:41:12     WARNING    warning:/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/osgeo/gdal.py:107: DeprecationWarning: gdal.py was placed in a namespace, it is now available as osgeo.gdal
              DeprecationWarning)
             
             traceback: File "", line 1, in 
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 354, in startPlugin
              if not _startPlugin(packageName):
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/__init__.py", line 11, in classFactory
              from .plugin import GeocatBridge
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/plugin.py", line 13, in 
              from .ui.bridgedialog import BridgeDialog
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/bridgedialog.py", line 8, in 
              from .publishwidget import PublishWidget
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/publishwidget.py", line 49, in 
              from geocatbridge.publish.publishtask import PublishTask, ExportTask
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 28, in 
              from .exporter import exportLayer
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Users/gavinfleming/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/exporter.py", line 2, in 
              import gdal
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 744, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "", line 983, in _find_and_load
              File "", line 967, in _find_and_load_unlocked
              File "", line 677, in _load_unlocked
              File "", line 728, in exec_module
              File "", line 219, in _call_with_frames_removed
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/gdal.py", line 3, in 
              deprecation_warn('gdal')
              File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/osgeo/gdal.py", line 107, in deprecation_warn
              DeprecationWarning)
```

**Comment by volaya** [comment]
Great, thanks. I am closing this
