### ISSUE TITLE
AttributeError: type object 'RenderUnit' has no attribute 'RenderPoints' 

### ISSUE THREAD

**Issue by aaime** [GeoCat/qgis-bridge-plugin#116]
This happens the moment I add a new shapefile layer to a project in QGIS 3.8. The layer is added anyways to the project.

From the crash report:

```
AttributeError: type object 'RenderUnit' has no attribute 'RenderPoints' 
Traceback (most recent call last):
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 59, in updateForCurrentLayer
    sld, _, sldWarnings = layerStyleAsSld(layer)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 17, in layerStyleAsSld
    geostyler, icons, warnings = togeostyler.convert(layer)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 32, in convert
    geostyler = processLayer(layer)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 78, in processLayer
    rules.extend(processRule(rule,None,layer.opacity(),layer))
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 393, in processRule
    symbolizers = _createSymbolizers(rule.symbol(),layerOpacity)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 535, in _createSymbolizers
    symbolizer = _createSymbolizer(sl, opacity)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 551, in _createSymbolizer
    symbolizer = _lineSymbolizer(sl, opacity)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 606, in _lineSymbolizer
    sl, "line_width", QgsSymbolLayer.PropertyStrokeWidth)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 504, in _symbolProperty
    v = _handleUnits(v, units, propertyConstant)
  File "/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 453, in _handleUnits
    if units in ["Point", QgsUnitTypes.RenderUnit.RenderPoints]:
AttributeError: type object 'RenderUnit' has no attribute 'RenderPoints'


Python version: 3.6.9 (default, Apr 18 2020, 01:56:04) [GCC 8.4.0] 
QGIS version: 3.8.1-Zanzibar Zanzibar, dcd95cc648 

Python Path:
/usr/share/qgis/python
/home/user/.local/share/QGIS/QGIS3/profiles/default/python
/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/usr/lib/python3.6/dist-packages
/home/user/.local/share/QGIS/QGIS3/profiles/default/python
/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vector_tiles_reader/ext-libs
.
/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs
/home/user/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle
```

**Comment by rjdini** [comment]
Same issue using GeoCatBridge 4.0.2 installed on  QGIS 3.12.3-Bucureșt running on ubuntu 18.05

**Comment by seabilwe** [comment]
I experienced a similar issue, but I was adding a new table (using GeoCatBridge 4.0.2 installed on QGIS 3.12.3). Editing and loading a table caused QGIS to crash, the crash stopped when the plugin was disabled

**Comment by GeoSander** [comment]
Thanks @aaime for reporting this issue and @volaya for fixing it :)
