### ISSUE TITLE
invalid layer throws Python Stacktrace

### ISSUE THREAD

**Issue by rduivenvoorde** [GeoCat/qgis-bridge-plugin#121]
To reproduce, load an invalid wms layer:

I had an invalid layer in my layerlist, and just upon clicking on it the following error was served to me:

![Screenshot-20201013104410-1444x596](https://user-images.githubusercontent.com/731673/95837671-246b9e00-0d41-11eb-8d7a-47a0a0876682.png)

```
AttributeError: 'NoneType' object has no attribute 'opacity' 
Traceback (most recent call last):
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 59, in updateForCurrentLayer
    sld, _, sldWarnings = layerStyleAsSld(layer)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 17, in layerStyleAsSld
    geostyler, icons, warnings = togeostyler.convert(layer)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 32, in convert
    geostyler = processLayer(layer)
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 85, in processLayer
    rasterSymbolizer(layer)]}]
  File "/home/richard/.local/share/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 128, in rasterSymbolizer
    symbolizer = {"kind": "Raster", "opacity": renderer.opacity(),
AttributeError: 'NoneType' object has no attribute 'opacity'
```

Seems an easy fix, just check if `layer is not None` somewhere?

To reproduce, run the following code in a python console.
You will end up with one valid and one invalid layer, just clicking on the invalid layer already throws that error with me (I'm on current master version)

```
# see https://qgis.nl/2017/02/01/topotijdreis-kaartlagen-in-qgis/?

# create a layer group
layer_group = QgsProject.instance().layerTreeRoot().insertGroup(0, 'TopoTijdReis')
# make the group mutually exlusive (one layer visible at a time)
layer_group.setIsMutuallyExclusive(True)
# copied from https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/

years = ['2008', '1817']

# for every year, create a layer
for year in years:
  layer = QgsRasterLayer("tileMatrixSet=default028mm&crs=EPSG:28992&layers=Historische_tijdreis_{0}&styles=default&format=image/jpgpng&url=https://tiles.arcgis.com/tiles/nSZVuSZjHpEZZbRo/arcgis/rest/services/Historische_tijdreis_{1}/MapServer/WMTS/".format(year, year), "TopoTijdReis {0}".format(year), "wms")
  # add it to the layer registry, without showing it yet
  # False, meaning not ready to add to legend
  if hasattr(qgis.core, 'QgsMapLayerRegistry'):
    # QGIS 2.x
    QgsMapLayerRegistry.instance().addMapLayer(layer, False)
  else:
    # QGIS 3.x
    QgsProject.instance().addMapLayer(layer, False)
  # add it on top of the group
  layer_group.insertLayer(0, layer)

print('go')
```

**Comment by GeoSander** [comment]
This should be solved in the upcoming 4.1 release. Only supported layers will be handled by the StyleViewer (previously Multistyler).
