### ISSUE TITLE
Right-click on OSM WMS layer results in BridgeStyle exception

### ISSUE THREAD

**Issue by GeoSander** [GeoCat/qgis-bridge-plugin#122]
1. OSM layer added to QGIS (using QuickMapServices plugin)
2. Right-click (context menu) on OSM layer
3. Bridge throws error. Stack trace:

```
KeyError: 'Z' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\geocatbridge\ui\multistylerdialog.py", line 64, in updateForCurrentLayer
    mapbox, _, mapboxWarnings = layerStyleAsMapbox(layer)
  File "C:\OSGEO4~1\apps\qgis\python\plugins\geocatbridge\libs\bridgestyle\bridgestyle\qgis\__init__.py", line 45, in layerStyleAsMapbox
    mbox, mbWarnings = mapboxgl.fromgeostyler.convert(geostyler)
  File "C:\OSGEO4~1\apps\qgis\python\plugins\geocatbridge\libs\bridgestyle\bridgestyle\mapboxgl\fromgeostyler.py", line 16, in convert
    layers = processLayer(geostyler)
  File "C:\OSGEO4~1\apps\qgis\python\plugins\geocatbridge\libs\bridgestyle\bridgestyle\mapboxgl\fromgeostyler.py", line 74, in processLayer
    layers = processRule(rule, layer["name"], ruleNumber)
  File "C:\OSGEO4~1\apps\qgis\python\plugins\geocatbridge\libs\bridgestyle\bridgestyle\mapboxgl\fromgeostyler.py", line 92, in processRule
    layers = [processSymbolizer(s) for s in rule["symbolizers"]]
  File "C:\OSGEO4~1\apps\qgis\python\plugins\geocatbridge\libs\bridgestyle\bridgestyle\mapboxgl\fromgeostyler.py", line 92, in 
    layers = [processSymbolizer(s) for s in rule["symbolizers"]]
  File "C:\OSGEO4~1\apps\qgis\python\plugins\geocatbridge\libs\bridgestyle\bridgestyle\mapboxgl\fromgeostyler.py", line 186, in processSymbolizer
    s["Z"] = sl["Z"]
KeyError: 'Z'


Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.12.3-București București, 8234261527 

Python Path:
C:/OSGEO4~1/apps/qgis/./python
C:/Users/admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/OSGEO4~1/apps/qgis/./python/plugins
C:\OSGEO4~1\apps\Python37
C:\OSGEO4~1\apps\Python37\Scripts
C:\OSGeo4W64\bin\python37.zip
C:\OSGEO4~1\apps\Python37\DLLs
C:\OSGEO4~1\apps\Python37\lib
C:\OSGeo4W64\bin
C:\Users\admin\AppData\Roaming\Python\Python37\site-packages
C:\OSGEO4~1\apps\Python37\lib\site-packages
C:/Users/admin/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\OSGEO4~1\apps\qgis\python\plugins\geocatbridge\libs\bridgestyle
```

**Comment by GeoSander** [comment]
Fixed in 4.1
