### ISSUE TITLE
Error while publishing via geocat bridge

### ISSUE THREAD

**Issue by OatNoppasin** [GeoCat/qgis-bridge-plugin#134]
My machine using 
- QGIS 3.18.3
- Apache Tomcat/9.0.50

When I try to publish map layer, The error show as below:
2021-08-03T13:34:50     CRITICAL    Traceback (most recent call last):
              File "C:/Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\tasks.py", line 111, in run
              self.geodata_server.prepareForPublishing(self.only_symbology)
              File "C:/Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\models\geoserver.py", line 122, in prepareForPublishing
              self.clearWorkspace()
              File "C:/Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\models\geoserver.py", line 779, in clearWorkspace
              self._createWorkspace()
              File "C:/Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\models\geoserver.py", line 920, in _createWorkspace
              self.request(url, data=ws, method="post")
              File "C:/Users/PC/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\bases.py", line 225, in request
              result.raise_for_status()
              File "C:\OSGEO4~1\apps\Python37\lib\site-packages\requests\models.py", line 941, in raise_for_status
              raise HTTPError(http_error_msg, response=self)
             requests.exceptions.HTTPError: 500 Server Error: for url: http://localhost:8080/geoserver/rest/workspaces

How can i fixed it?

**Comment by GeoSander** [comment]
Hi @OatNoppasin,

I am not sure what caused this error, but the 500 indicates that something went wrong on the GeoServer side during the creation of the workspace. I highly recommend having a look at the GeoServer logs (if you can access the host directly or via the admin URL). There will probably be some Java exception there.

By the way, I noticed that you have been using a development version of Bridge.
It probably won't fix the issue, but we have just uploaded the official Bridge 4.1 release to the QGIS repo: https://plugins.qgis.org/plugins/geocatbridge/version/4.1.3/

Sander
