### ISSUE TITLE
Can't list or add a datastore for Geoserver

### ISSUE THREAD

**Issue by rfazimut** [GeoCat/qgis-bridge-plugin#191]
**Describe the bug**
With the current version, from the connection tab, I cannot add a database or iterate the list of database defined on the geoserver with this message:

  File "C:\Users/rfortin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\views\geoserver.py", line 184, in _addGeoserverPgDatastores
    datastores = list(chain.from_iterable(worker_result))
TypeError: 'KeyError' object is not iterable

**To Reproduce**
1. Add connection Geoserver
2. Specify parameter and credential
3. Select File-based...
4. Test Connection == OK
5. Change storage to Import into PostGIS database (managed by GeoServer)  
Datastore are defined on the server
6. CLick Add datastore
7. Specifiy parameter
8. Click OK
9. The error message shows.

**Expected behavior**
Datastore is added or listed from the Geoserver

**Screenshots**

**Environment info (please complete the following information):**
Bridge version: GeoCat Bridge 4.5.1 for QGIS 3.16+
QGIS version: 3.22.5-Białowieża (rev c2723178)
OS version: Windows 10 10.0.19045
Python version: 3.9.5 (rev 0a7dcbd)

**Additional context**
GeoServer 2.26

**Comment by GeoSander** [comment]
Thanks for reporting @rfazimut.

Two additional questions I have:

1. If there already is a PostGIS datastore on GeoServer (defined manually perhaps using the GS web UI - 
 not using Bridge), and you select `Import into PostGIS database (managed by GeoServer)` (so at step 5 above), can you at least confirm that the combobox below it gets populated with some existing datastores?

2. Which parameters (at step 7) do you specify? I don't mean the exact values (user, pass, etc.) but I would like to know which fields you are setting.

3. After step 8 (OK), does the "Add datastore" dialog close first before the error appears?

Thanks,
Sander

**Comment by rfazimut** [comment]
Hi!

Answer to your questions :


  1.  Yes. There are defined datastore on the Geoserver. The error come as soon as we select select Import into PostGIS database (managed by GeoServer)


  1.  Here an example
***@***.***



  1.  Yes.  It tries to refresh the list of datastore and we get the same error.


I tried also using the other option (direct connect) after a connection to the same PostGIS database as been defined.  In this case, we get a different message when we try to publish.

Errors:
Traceback (most recent call last):
File "C:\Users/rfortin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\tasks.py", line 129, in run
_publish(layer, publish_fields)
File "C:\Users/rfortin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\publish\tasks.py", line 65, in _publish
self.geodata_server.publishLayer(lyr, pub_fields)
File "C:\Users/rfortin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\models\geoserver.py", line 277, in publishLayer
self._publishVectorLayerFromPostgis(layer, db, fields)
File "C:\Users/rfortin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\models\geoserver.py", line 669, in _publishVectorLayerFromPostgis
self.request(ds_url, data=ds, method="post")
File "C:\Users/rfortin/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geocatbridge\servers\bases.py", line 279, in request
result.raise_for_status()
File "C:\PROGRA~1\QGIS32~1.5\apps\Python39\lib\site-packages\requests\models.py", line 941, in raise_for_status
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 500 Server Error: Server Error for url: http://192.168.10.207:8080/geoserver/rest/workspaces/evalzonage49048/datastores

At this point, we have been unable to publish layer to Geoserver other then using the geopackage option.

It is not clear to me if checking the option “Reference existing PostGIS tables (if exists)” will actually just publish the layer and not copy the data which is already there.  Is that what it is supposed to do?

Robert
T  450 466 6665 poste 213
C 438 8202056

De : Sander Schaminee ***@***.***>
Envoyé : 16 octobre 2024 16:30
À : GeoCat/qgis-bridge-plugin ***@***.***>
Cc : Robert Fortin ***@***.***>; Mention ***@***.***>
Objet : Re: [GeoCat/qgis-bridge-plugin] Can't list or add a datastore for Geoserver (Issue #191)


Thanks for reporting @rfazimut<https://github.com/rfazimut>.

Two additional questions I have:

  1.  If there already is a PostGIS datastore on GeoServer (defined manually perhaps using the GS web UI -
not using Bridge), and you select Import into PostGIS database (managed by GeoServer) (so at step 5 above), can you at least confirm that the combobox below it gets populated with some existing datastores?
  2.  Which parameters (at step 7) do you specify? I don't mean the exact values (user, pass, etc.) but I would like to know which fields you are setting.
  3.  After step 8 (OK), does the "Add datastore" dialog close first before the error appears?

Thanks,
Sander
