### ISSUE TITLE
md publish succesfull despite error 500

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#20]
Even while publish url threw error, the bridge publish status panel shows the publish as succefull, expected is to see status publish=false, hopefully can read from the error 500 page what is wrong with the publication

```
Errors:
Traceback (most recent call last): File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 106, in run self.metadataServer.publishLayerMetadata(layer, wms) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geonetwork.py", line 86, in publishLayerMetadata self.publishMetadata(mefFilename) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geonetwork.py", line 176, in publishMetadata r.raise_for_status() File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: https://example.com/geonetwork/srv/eng/mef.import 
```

**Comment by pvgenuchten** [comment]
Did some research using network-analyser:


mef.import function returns:

```xml
<error id="error">java.lang.Exception: Missing siteId parameter from info.xml file</error>
```

publish PUT command throws

```xml
<apiError>
	<code>runtime_exception</code>
	<description>Request method 'PUT' not supported</description>
	<message>HttpRequestMethodNotSupportedException</message>
</apiError>
```

info.xml returns a html containing:

```
HTTP Status 403 – Forbidden
Expected CSRF token not found. Has your session expired?
The server understood the request but refuses to authorize it.
```

**Comment by pvgenuchten** [comment]
i found the error for this problem, it is [here](https://github.com/geonetwork/core-geonetwork/issues/4107)
make sure to set the uuid of the catalogue in settings, before using bridge (hope it will be resolved in gn soon)
