### ISSUE TITLE
publish second time fails

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#25]
when publishing the same project to geoserver in workspace mode, it fails with 403, probably it treis to overwrite an existing layer, which fails

```
2019-10-19T18:10:52     CRITICAL    Traceback (most recent call last):
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 69, in run
              self.geodataServer.prepareForPublishing(self.onlySymbology)
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 57, in prepareForPublishing
              self.deleteWorkspace()
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 271, in deleteWorkspace
              r = self.request(url, method="delete")
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/serverbase.py", line 50, in request
              r.raise_for_status()
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status
              raise HTTPError(http_error_msg, response=self)
             requests.exceptions.HTTPError: 403 Client Error: 403 for url: https://victortest0830.geocat.live/geoserver/rest/workspaces/point-no-angle5
```

**Comment by volaya** [comment]
fixed in https://github.com/GeoCat/qgis-bridge-plugin/commit/a7aa72db8b1fb05a19d8f51b147a69f0029eb70b
