### ISSUE TITLE
gn mef import fails when uuid already exists

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#26]
bridge log:

```
Traceback (most recent call last): File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 107, in run self.metadataServer.publishLayerMetadata(layer, wms) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geonetwork.py", line 86, in publishLayerMetadata self.publishMetadata(mefFilename) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geonetwork.py", line 176, in publishMetadata r.raise_for_status() File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 935, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: for url: http://192.168.99.101:32771/geonetwork/srv/eng/mef.import 
```

Api error (bridge could read the api error and display the error, although the error is not very obvious...):

```
<error id="error">No entity found with id: 123; nested exception is javax.persistence.EntityNotFoundException: No entity found with id: 123</error>
```

123 seems the internal id of current metadata

From gn logs (seems a duplicate uuid):

```
Caused by: org.h2.jdbc.JdbcBatchUpdateException: Unique index or primary key violation: "UK_E9W46I6V429H02TMYNM3EEFIY_INDEX_1 ON PUBLIC.METADATA(UUID) VALUES ( /* 123 */ '8d652d55-d431-595e-a250-b8590fbf3a91' )"; SQL statement:
insert into Metadata (data, changeDate, createDate, displayorder, doctype, extra, popularity, rating, root, schemaId, title, isTemplate, isHarvested, harvestUri, harvestUuid, groupOwner, owner, source, uuid, id) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) [23505-174]
```

Code should verify if uuid already exists, if so, do an update in stead of insert

**Comment by volaya** [comment]
should be fixed now, since we are now using the uuidAction=overwrite parameters
