### ISSUE TITLE
KeyError: 'GeoServer1' at server config

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#28]
error below happens incidentally when switching from editing server1 to create new server

```
KeyError: 'GeoServer1' 
Traceback (most recent call last):
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/serverconnectionswidget.py", line 292, in 
    menu.addAction("GeoNetwork", lambda: self._addServer("GeoNetwork", GeonetworkServer))
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/serverconnectionswidget.py", line 321, in _addServer
    if self.saveCurrentServer():
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/serverconnectionswidget.py", line 162, in saveCurrentServer
    removeServer(self.currentServer.name)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/servers.py", line 46, in removeServer
    del _servers[name]
KeyError: 'GeoServer1'
```

workaround, close publish window, reopen

**Comment by volaya** [comment]
fixed in https://github.com/GeoCat/qgis-bridge-plugin/commit/cb3f7f580233ce60f71f303e6bcb6db9ff3c3b82
