### ISSUE TITLE
workspace error when publishing

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#29]
geoserver 2.13
workspase mode

when publishing to geoserver

```
2019-10-23T00:44:39     CRITICAL    Traceback (most recent call last):
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 82, in run
              self.geodataServer.prepareForPublishing(self.onlySymbology)
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 57, in prepareForPublishing
              self.deleteWorkspace()
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 272, in deleteWorkspace
              if self.workspaceExists():
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 231, in workspaceExists
              return self._exists(url, "workspace", self._workspace)
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 208, in _exists
              r = self.request(url)
              File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/serverbase.py", line 51, in request
              r = req_method(url, headers=headers, data=data, auth=(username, password))
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 72, in get
              return request('get', url, params=params, **kwargs)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/api.py", line 58, in request
              return session.request(method=method, url=url, **kwargs)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 494, in request
              prep = self.prepare_request(req)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/sessions.py", line 437, in prepare_request
              hooks=merge_hooks(request.hooks, self.hooks),
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 305, in prepare
              self.prepare_url(url, params)
              File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/requests/models.py", line 379, in prepare_url
              raise MissingSchema(error)
             requests.exceptions.MissingSchema: Invalid URL 'https%3A//victortest0830.geocat.live/geoserver/rest/workspaces.json': No schema supplied. Perhaps you meant http://https%3A//victortest0830.geocat.live/geoserver/rest/workspaces.json?
```

**Comment by volaya** [comment]
Fixed in https://github.com/GeoCat/qgis-bridge-plugin/commit/2f1849a451453b5cfaa0c6fc59c546d51d8874a4
