### ISSUE TITLE
GeoCat Live publishing questions and error

### ISSUE THREAD

**Issue by jodygarnett** [GeoCat/qgis-bridge-plugin#33]
It could be I am just not familiar with the QGIS login management (remember storing it in a vault in QGIS 2).  

I am not quite sure where my GeoCat Live credentials go on this screen

![image](https://user-images.githubusercontent.com/629681/67518493-e75f5500-f672-11e9-9259-3e08876d280a.png)

Also not quite sure about "realm" 
![image](https://user-images.githubusercontent.com/629681/67518463-da426600-f672-11e9-82e4-6592c065afad.png)

Going to assume something like this:
![image](https://user-images.githubusercontent.com/629681/67518684-40c78400-f673-11e9-8384-088d222c9c31.png)

**Comment by jodygarnett** [comment]
Update: Hitting `Save` a second time results in an error:

```
An error has occurred while executing Python code: 

KeyError: 'GeoCat Live1' 
Traceback (most recent call last):
  File "/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/serverconnectionswidget.py", line 410, in saveButtonClicked
    if self.saveCurrentServer():
  File "/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/serverconnectionswidget.py", line 162, in saveCurrentServer
    removeServer(self.currentServer.name)
  File "/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/servers.py", line 46, in removeServer
    del _servers[name]
KeyError: 'GeoCat Live1'


Python version: 3.7.3 (default, Mar 27 2019, 09:23:15) [Clang 10.0.1 (clang-1001.0.46.3)] 
QGIS version: 3.8.3-Zanzibar Zanzibar, 685d8b15d2 

Python Path:
/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python
/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS3.8.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/lib-dynload
/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages
/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7/site-packages/geos
/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python37.zip
/Applications/QGIS3.8.app/Contents/Frameworks/Python.framework/Versions/Current/lib/python3.7
/Applications/QGIS3.8.app/Contents/Resources/python
/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs
/Users/jgarnett/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle
```

**Comment by volaya** [comment]
Fixed in https://github.com/GeoCat/qgis-bridge-plugin/commit/1d3147166c1501c1ae552bee71f48521f51a5a28

You are not supposed to use the geocat live credentials in the plugin, since they are useless until we set up sinngle sign-on. For now, you have to use that to log in the web, and from there get the credentials of both the geonetwork and the geoserver instances. By entering your username, it can find the URLs of both services

The 'realm' parameter should be left blank
