### ISSUE TITLE
error creating zip while publishing

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#35]
```
Traceback (most recent call last): File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 103, in run self.geodataServer.publishLayer(layer, fields) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 72, in publishLayer self.publishStyle(layer) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 64, in publishStyle warnings = saveLayerStyleAsZippedSld(layer, styleFilename) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 32, in saveLayerStyleAsZippedSld z.write(icon, os.path.basename(icon)) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 1594, in write zinfo = ZipInfo.from_file(filename, arcname) File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/zipfile.py", line 484, in from_file st = os.stat(filename) FileNotFoundError: [Errno 2] No such file or directory: '' 
```

**Comment by volaya** [comment]
Looks like the icons have a null path sometimes. Not sure why it happens, and why only certain times, but this should prevent the error:

https://github.com/GeoCat/bridge-style/commit/e05f7fc6517886bbf4d0b496cea4b5211b6f8ae0
