### ISSUE TITLE
layers with space in layername fail in geoserver

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#64]
bridge tried to publish a layer with name containing a space, geoserver throws an error 500

from qgis:
```
Traceback (most recent call last): File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 132, in run self.geodataServer.setLayerMetadataLink(name, url) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 385, in setLayerMetadataLink r = self.request(resourceUrl, data=layer, method="put") File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/serverbase.py", line 60, in request r.raise_for_status() File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/requests/models.py", line 940, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 500 Server Error: Server Error for url: http://localhost:8080/geoserver/rest/workspaces/tz_elevations/datastores/Railway+OSM/featuretypes/Railway+OSM.json 
```

in geoserver (2.16):
```
Caused by: java.net.URISyntaxException: Illegal character in path at index 74: http://localhost:8080/geoserver/rest/workspaces/tz_elevations/layers/Roads OSM.json
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.checkChars(URI.java:3021)
	at java.net.URI$Parser.parseHierarchical(URI.java:3105)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URL.toURI(URL.java:963)
	at org.geoserver.catalog.impl.MetadataLinkInfoImpl.validate(MetadataLinkInfoImpl.java:97)
	... 137 more
2020-02-02 21:30:04,603 WARN [annotation.ExceptionHandlerExceptionResolver] - Resolved [com.thoughtworks.xstream.converters.ConversionException: Failed calling method
---- Debugging information ----
message             : Failed calling method
cause-exception     : java.lang.IllegalArgumentException
cause-message       : Not a valid URL: http://localhost:8080/geoserver/rest/workspaces/tz_elevations/layers/Roads OSM.json
method              : org.geoserver.catalog.impl.MetadataLinkInfoImpl.readResolve()
```

in stead of a warning i suggest to replace spaces by '_' or throw an error before publishing. data is available at http://www.tzgisug.org/wp/qgis-example-data-for-tanzania-2, problematic layer is the "roads osm" layer

**Comment by pvgenuchten** [comment]
duplicate of #54
