### ISSUE TITLE
zerodevision in mapbox generation

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#65]
error when converting style to mapbox

```
ZeroDivisionError: float division by zero 
Traceback (most recent call last):
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 62, in updateForCurrentLayer
    mapbox, _, mapboxWarnings = layerStyleAsMapbox(layer)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 40, in layerStyleAsMapbox
    mbox, mbWarnings = mapboxgl.fromgeostyler.convert(geostyler)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/mapboxgl/fromgeostyler.py", line 10, in convert
    layers = processLayer(geostyler)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/mapboxgl/fromgeostyler.py", line 31, in processLayer
    layers = processRule(rule, layer["name"])
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/mapboxgl/fromgeostyler.py", line 45, in processRule
    minzoom = _toZoomLevel(scale["min"])
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/mapboxgl/fromgeostyler.py", line 25, in _toZoomLevel
    return int(math.log(1000000000 / scale, 2))
ZeroDivisionError: float division by zero
```

data is available at http://www.tzgisug.org/wp/qgis-example-data-for-tanzania-2, problematic layer is the 'roads osm' layer

**Comment by pvgenuchten** [comment]
problem seems related to scale is 0 (in scaledenominator); in stead use 0.001
