### ISSUE TITLE
error transforming numeric font marker

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#69]
I used https://github.com/StephSaephan/QGIS-USGS-TNM-Style-Template template to style topo data from https://viewer.nationalmap.gov/basic, in layer structures an error occurs when converting the style

```
TypeError: object of type 'float' has no len() 
Traceback (most recent call last):
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/ui/multistylerdialog.py", line 59, in updateForCurrentLayer
    sld, _, sldWarnings = layerStyleAsSld(layer)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/__init__.py", line 17, in layerStyleAsSld
    geostyler, icons, warnings = togeostyler.convert(layer)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 28, in convert
    geostyler = processLayer(layer)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 70, in processLayer
    rules.extend(processRule(rule))
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 239, in processRule
    symbolizers = _createSymbolizers(rule.symbol())
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 345, in _createSymbolizers
    symbolizer = _createSymbolizer(sl, opacity)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 375, in _createSymbolizer
    symbolizer = _fontMarkerSymbolizer(sl, opacity)
  File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/libs/bridgestyle/bridgestyle/qgis/togeostyler.py", line 388, in _fontMarkerSymbolizer
    if len(character) == 1:
TypeError: object of type 'float' has no len()
```

Style of this layer 

![image](https://user-images.githubusercontent.com/299829/73616683-d1204800-4616-11ea-89da-a57c096edc1b.png)

Maybe the problem is in this font marker, which uses a number-character, not a character?

![image](https://user-images.githubusercontent.com/299829/73616702-13e22000-4617-11ea-9a4d-e80489c04f5b.png)

**Comment by pvgenuchten** [comment]
replacing the number with a simple marker solved the case, so it is related to the fact this character is a number
