### ISSUE TITLE
div construct in markerline fails sld

### ISSUE THREAD

**Issue by pvgenuchten** [GeoCat/qgis-bridge-plugin#70]
I used https://github.com/StephSaephan/QGIS-USGS-TNM-Style-Template template to style topo data from https://viewer.nationalmap.gov/basic, For layer nhdline i got this error:

```
Traceback (most recent call last): File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/publishtask.py", line 128, in run self.geodataServer.publishLayer(layer, fields) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 77, in publishLayer self.publishStyle(layer) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 73, in publishStyle self._publishStyle(layer.name(), styleFilename) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/geoserver.py", line 404, in _publishStyle self.request(url, f.read(), method, headers) File "/Users/geocat/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/geocatbridge/publish/serverbase.py", line 60, in request r.raise_for_status() File "/Applications/QGIS3.10.app/Contents/MacOS/../Resources/python/requests/models.py", line 940, in raise_for_status raise HTTPError(http_error_msg, response=self) requests.exceptions.HTTPError: 400 Client Error: Style error. For input string: "['Div'," for url: http://localhost:8080/geoserver/rest/workspaces/USGSTNM_Template_QGIS3_Draft/styles?name=NHDLine 
```

on geoserver:

```
2020-02-02 23:28:03,456 INFO [rest.catalog] - PUT layer USGSTNM_Template_QGIS3_Draft:NHDFlowline
2020-02-02 23:28:03,743 ERROR [rest.catalog] - For input string: "['Div',"
2020-02-02 23:28:03,750 ERROR [geoserver.rest] - Style error. For input string: "['Div',"
org.geoserver.rest.RestException 400 BAD_REQUEST: Style error. For input string: "['Div',"
	at org.geoserver.rest.catalog.StyleController.parseSld(StyleController.java:572)
	at org.geoserver.rest.catalog.StyleController.stylePost(StyleController.java:178)
	at sun.reflect.GeneratedMethodAccessor469.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
```

on the generated sld for value "reef" & "tunnel" (both use the markerline symbology) i noticed this generated construct:

```
 <CssParameter name="stroke-dasharray">['Div', 14.36220472458, 2] 8.31496063002</CssParameter>
```
(similar in geostyler:  "size": [ "Div", 14.36220472458, 2 ])

**Comment by volaya** [comment]
should be fixed now

**Comment by pvgenuchten** [comment]
resolved
